## 1. 파이썬 파일 처리

In [359]:
sample_file = 'data/sample.txt'

In [360]:
# 파일을 open하여 전체 내용을 읽어서 출력

with open(sample_file, mode='rt') as f:
    content = f.read()
    print(content)

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

----- 끝 -----

In [361]:
# 파일을 open하고 한 줄씩 읽어서 출력하기
with open(sample_file, 'r') as f:
    lines = f.readlines()
    print(lines)
    for line in lines:
        print(line, end="")

print("----- 끝 -----")

['나의 속도로\n', '\n', '조금 늦어도 괜찮다.\n', '남들과 같은 길을 갈 필요도 없다.\n', '\n', '오늘 배운 것 하나,\n', '오늘 해결한 문제 하나가\n', '조금씩 나의 실력이 된다.\n', '\n', '결과가 보이지 않는 날에도\n', '나는 앞으로 가고 있다.\n', '\n', '빠르게 가는 것보다\n', '멈추지 않는 것이 중요하다.\n', '\n', '오늘의 작은 한 걸음이\n', '내일의 나를 만든다.\n', '\n', '나는 늦은 것이 아니라\n', '나의 속도로 가고 있다.\n']
나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [362]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며,
# 각 줄 끝의 \n도 포함해서 가져옵
with open(sample_file, 'r') as f:
    for line in f:
        print(line, end="")

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [363]:
# 여러 개의 파일 읽기 (모든 txt 파일을 읽어서 출력하기)
import glob

txt_file_pattern = "data/*.txt"
files = glob.glob(txt_file_pattern)
print(files)

for file in files:
    print(file)
    with open(file, "r") as f:
        print(f.read())

print("----- 끝 -----")

['data\\sample.txt']
data\sample.txt
나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

----- 끝 -----

## 2. 파이썬 문자열 다루기

In [364]:
# 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
b1.strip()

'작은 일에 성실한 사람은      큰일에도 성실하고'

In [365]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text = text.strip('.')
text

'작은 일에 성실한 사람은, 큰일에도 성실하고'

In [366]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text.split(",")

['....작은 일에 성실한 사람은', ' 큰일에도 성실하고....']

In [367]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
numbers.split(".")

['1', ' 2', ' 3', ' 4', ' 5', ' 6']

## 3. 판다스로 데이터 가져오기

In [368]:
# 판다스 설치
!pip install pandas

Requirement already satisfied: pandas in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [369]:
# 연습용 sample_data.csv 로딩하기
sample_file = 'data/sample_data.csv'

import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [370]:
sample_df.to_csv('data/sampel_data_copy.csv', index=False)

In [371]:
df2 = pd.read_csv('data/sampel_data_copy.csv')
df2

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [372]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'

In [373]:
# 데이터를 읽으면서 탭을 기준으로 분리하여 데이터 프레임으로 만들기
t_df = pd.read_csv(titanic_data, sep="\t")
t_df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [374]:
# 앞부분 확인
sample_df.head()

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston

In [375]:
# 뒷부분 확인
t_df.tail

<bound method NDFrame.tail of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
151          152         1       1
152          153         0       3
153          154         0       3
154          155         0       3
155          156         0       1

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1
152                                   Meo, Mr. Alfonzo    male  55.5      0
153                    van Billiard, Mr. Austin Blyler    male  40.5      0
154                              Olsen, Mr. Ole Martin    male   NaN      0
155                        Williams, Mr. Charles Duane    male  51.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
151      0            113776  66.6000    C2        S
152      0        A.5. 11206   8.0500   NaN        S
153      2          A/5. 851  14.5000   NaN        S
154      0         Fa 265302   7.3125   NaN        S
155      1          PC 17597  61.3792   NaN        C

[156 rows x 12 columns]>

In [376]:
# 데이터 개수/형태 확인
t_df.shape

(156, 12)

In [377]:
#데이터의 기본 통계치 보기
sample_df.describe()

             Age
count   5.000000
mean   26.200000
std     4.147288
min    22.000000
25%    24.000000
50%    24.000000
75%    29.000000
max    32.000000

In [378]:
# 데이터 구성 정보 확인하기
t_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [379]:
# 타이타닉 데이터 구조 및 구성 확인하기
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     5 non-null      float64
 2   Gender  7 non-null      str
 3   City    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 356.0 bytes

### 4-2. 컬럼명과 인덱스 정리

In [380]:
# 데이터프레임 복사하기
sample_backup_df = sample_df.copy()
sample_backup_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [381]:
# 열 이름 변경하기 : 모두 소문자로 변경
new_cols = []
for col in sample_df.columns:
    new_cols.append(col.lower())
sample_df.columns = new_cols
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [382]:
sample_df = sample_df.rename(columns=str.lower)
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [383]:
sample_df = sample_df.rename(columns=str.capitalize)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [384]:
# 컬럼명의 앞글자는 소문자로, 나머지는 대문자로 수정

In [385]:
sample_df = sample_backup_df.copy()
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [386]:
# index 확인
sample_df.index

RangeIndex(start=0, stop=7, step=1)

In [387]:
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [388]:
# 행 데이터 삭제하기
drop_index = [2, 4, 152, 154]
t_df = t_df.drop(drop_index, axis=0)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [389]:
# index를 0부터 순서대로 assign 되도록 reset하기
t_df.reset_index(drop=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [390]:
t_df = t_df.rename(columns=str.lower)
t_df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [391]:
# 컬럼 PassengeId를 index로 설정하기
t_df = t_df.set_index('passengerid')
t_df

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...
150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [392]:
# 현재 index (pessengerid)를 컬럼으로 만들고, index를 RangeIndex로 reset하기
t_df = t_df.reset_index()
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-3. 데이터 정렬

In [393]:

# 'age' 기준으로 정렬
t_df = t_df.sort_values(by='age', ascending=False)
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
114,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
31,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
92,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [394]:
# 'age' 기준으로 내림차순으로 정렬

In [395]:
# 'age', 'pclass'를 기준으로 정렬
t_df.sort_values(by=['pclass', 'age'], ascending=False)

# pclass는 오름차순으로 정렬, age는 내림차순으로 정렬

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
114,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
92,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
130,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5000,NaN,S
127,130,0,3,"Ekstrom, Mr. Johan",male,45.0,0,0,347061,6.9750,NaN,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
25,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
134,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S
29,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
53,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
62,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C

In [396]:
# index를 기준으로 정렬
t_df = t_df.sort_index()
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-4. 데이터 접근/추출
* 범위 지정 : 직접 지정, 인덱서 이용
* 조건 지정

In [397]:
score_dict={'이름': ['정약용', '이순신', '이율곡', '홍길동'],
            '국어' : [70, 100, 90, 85],
            '영어' : [80, 80, 95, 100],
            '수학' : [100, 70, 90, 90]}
score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [398]:

# 행 지정 -> 슬라이싱
score_df[1:3]

    이름   국어  영어  수학
1  이순신  100  80  70
2  이율곡   90  95  90

In [399]:
# 열 접근
score_df.이름

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: str

In [400]:
# 특정 (행,열)의 데이터 접근
score_df[:2][['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100

In [401]:
# 인덱서 이용 : 레이블(이름) 인덱서
# 행 접근
score_df.loc[1]

이름    이순신
국어    100
영어     80
수학     70
Name: 1, dtype: object

In [402]:
# 열 접근
score_df.loc[:, '국어']

0     70
1    100
2     90
3     85
Name: 국어, dtype: int64

In [403]:
# (행,열) 접근
score_df.loc[1, '국어']

np.int64(100)

In [404]:
# 인덱서 이용 : 위치(숫자) 인덱서
# 행 접근
score_df.iloc[1]

이름    이순신
국어    100
영어     80
수학     70
Name: 1, dtype: object

In [405]:
# 열 접근
score_df.iloc[:, 1]

0     70
1    100
2     90
3     85
Name: 국어, dtype: int64

In [406]:
# (행,열) 접근
score_df.iloc[1, 1]

np.int64(100)

In [407]:
# 조건 지정 추출 : Boolean Indexing
# 직접 지정 방식으로 행 추출
score_df[score_df['국어'] >= 90]

    이름   국어  영어  수학
1  이순신  100  80  70
2  이율곡   90  95  90

In [408]:
# 인덱서 방식으로 행 추출
score_df.loc[score_df['국어'] >= 90]

    이름   국어  영어  수학
1  이순신  100  80  70
2  이율곡   90  95  90

In [409]:
# (행,열) 데이터 추출
score_df.loc[score_df['국어'] >= 90, ['이름', '수학']]

    이름  수학
1  이순신  70
2  이율곡  90

In [410]:
# 열 데이터에 조건 지정
score_df.loc[:,score_df.columns != '영어']

    이름   국어   수학
0  정약용   70  100
1  이순신  100   70
2  이율곡   90   90
3  홍길동   85   90

In [411]:
score_df.loc[:,score_df.dtypes == 'int']

    국어   영어   수학
0   70   80  100
1  100   80   70
2   90   95   90
3   85  100   90

## 타이타닉 데이터 추가 실습

In [412]:
t_df.sort_values(by=['age', 'pclass']) # 오름차순 정렬
t_df.sort_values(by=['age', 'pclass'], ascending=False) # 내림차순 정렬

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
114,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
31,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
92,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
15,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
29,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
53,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
62,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C

In [413]:
t_df[0:5] #titanic_df.head()와 실행 결과 동일함
t_df[0:1] #첫 행만 가져오기
t_df[::3] #3개씩 건너서 출력함
t_df[::-1] #행의 순서를 거꾸로 출력함

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [414]:
t_df[:3]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [415]:
len(t_df.columns)

12

In [416]:
t_df[t_df.columns[0]]

0        1
1        2
2        4
3        6
4        7
      ...
147    150
148    151
149    152
150    154
151    156
Name: passengerid, Length: 152, dtype: int64

In [417]:
t_df[t_df.columns[11]] # 마지막 열을 1차원 배열의 Series객체로 추출
# titanic_df[titanic_df.columns[-1]]

0      S
1      C
2      S
3      Q
4      S
      ..
147    S
148    S
149    S
150    S
151    C
Name: embarked, Length: 152, dtype: str

In [418]:
age=t_df['age']
print(type(age))

<class 'pandas.Series'>

In [419]:
t_df['age'] # 'age' 열을 1차원 배열인 Series 객체로 추출
t_df.age

0      22.0
1      38.0
2      35.0
3       NaN
4      54.0
       ...
147    42.0
148    51.0
149    22.0
150    40.5
151    51.0
Name: age, Length: 152, dtype: float64

In [420]:
print(t_df[t_df.columns[0]][0])  # 첫 번째 열의 첫 번째 값
print(t_df['age'][0])  # age 열의 첫 번째 값
print(t_df[t_df.columns[0]][2])
print(t_df[t_df.columns[-1]][0])
type(t_df[t_df.columns[0]][0])  # str

1
22.0
4
S

numpy.int64

In [421]:
t_df[t_df.columns[0]][2:6]  # 2번부터 5번 행까지
t_df[t_df.columns[0]][:-1]  # 마지막 행 제외
t_df[t_df.columns[0]][::3]  # 3개의 step으로 슬라이싱
t_df[t_df.columns[0]][-1:]  # 마지막 행만 추출
t_df[t_df.columns[0]][::-1]  # 행을 역순으로 출력

151    156
150    154
149    152
148    151
147    150
      ...
4        7
3        6
2        4
1        2
0        1
Name: passengerid, Length: 152, dtype: int64

In [422]:
t_df[['pclass', 'name', 'sex']]  # DataFrame 추출 
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]]  # DataFrame 추출

     pclass                                               name     sex
0         3                            Braund, Mr. Owen Harris    male
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
3         3                                   Moran, Mr. James    male
4         1                            McCarthy, Mr. Timothy J    male
..      ...                                                ...     ...
147       2                  Byles, Rev. Thomas Roussel Davids    male
148       2                         Bateman, Rev. Robert James    male
149       1                  Pears, Mrs. Thomas (Edith Wearne)  female
150       3                    van Billiard, Mr. Austin Blyler    male
151       1                        Williams, Mr. Charles Duane    male

[152 rows x 3 columns]

In [423]:
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]][2:15:3]  #  슬라이싱

    pclass                                          name     sex
2        1  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
5        3                Palsson, Master. Gosta Leonard    male
8        3               Sandstrom, Miss. Marguerite Rut  female
11       3                   Andersson, Mr. Anders Johan    male
14       3                          Rice, Master. Eugene    male

In [424]:
print(t_df[t_df.columns[0]][0])  
print(t_df[t_df.columns[0]][2])  
# print(t_df[t_df.columns[0]][-1])  # 실행 시 오류 발생! 
type(t_df[t_df.columns[0]][0])

1
4

numpy.int64

In [425]:
t_df.loc[0]

passengerid                          1
survived                             0
pclass                               3
name           Braund, Mr. Owen Harris
sex                               male
age                               22.0
sibsp                                1
parch                                0
ticket                       A/5 21171
fare                              7.25
cabin                              NaN
embarked                             S
Name: 0, dtype: object

In [426]:
t_df.loc[0:5]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [427]:
t_df.loc[0:10:2]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
6,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
10,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S

In [428]:
t_df.loc[:, 'age']

0      22.0
1      38.0
2      35.0
3       NaN
4      54.0
       ...
147    42.0
148    51.0
149    22.0
150    40.5
151    51.0
Name: age, Length: 152, dtype: float64

In [429]:
t_df.iloc[0]

passengerid                          1
survived                             0
pclass                               3
name           Braund, Mr. Owen Harris
sex                               male
age                               22.0
sibsp                                1
parch                                0
ticket                       A/5 21171
fare                              7.25
cabin                              NaN
embarked                             S
Name: 0, dtype: object

In [430]:
t_df.iloc[0:5]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [431]:
t_df[0:10:3]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [432]:
t_df.iloc[:, [0,2]]

     passengerid  pclass
0              1       3
1              2       1
2              4       1
3              6       3
4              7       1
..           ...     ...
147          150       2
148          151       2
149          152       1
150          154       3
151          156       1

[152 rows x 2 columns]

In [433]:
t_df.iloc[1:5, [0,2]]

   passengerid  pclass
1            2       1
2            4       1
3            6       3
4            7       1

In [434]:
t_df.loc[:, ['age', 'sex']]

      age     sex
0    22.0    male
1    38.0  female
2    35.0  female
3     NaN    male
4    54.0    male
..    ...     ...
147  42.0    male
148  51.0    male
149  22.0  female
150  40.5    male
151  51.0    male

[152 rows x 2 columns]

In [435]:
t_df.loc[3:7, ['age', 'sex']]

    age     sex
3   NaN    male
4  54.0    male
5   2.0    male
6  27.0  female
7  14.0  female

In [436]:
t_df.loc[2:5, 'survived':'age']

,survived,pclass,name,sex,age
2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
3,0,3,"Moran, Mr. James",male,NaN
4,0,1,"McCarthy, Mr. Timothy J",male,54.0
5,0,3,"Palsson, Master. Gosta Leonard",male,2.0

## 4-5. 그룹별로 요약하여 데이터 확인
* value_counts()
* groupby()
* pivot_table()

In [437]:
sample_file = 'data/sales_sample.csv'

In [438]:
# 샘플 파일 로딩
import pandas as pd
sales_df = pd.read_csv(sample_file)
sales_df

    지역   상품  판매수량   매출
0   서울  노트북     2  120
1   서울  태블릿     1   80
2   부산  노트북     2  100
3   부산  태블릿     1   70
4   서울  노트북     3  150
5   부산  노트북     1  110
6   대전  노트북     2  130
7   대전  태블릿     2   90
8   서울  태블릿     2  160
9   부산  태블릿     3  210
10  대전  노트북     1   65
11  대전  태블릿     1   45
12  서울  노트북     1   60
13  부산  노트북     3  150
14  대전  노트북     2  120
15  서울  태블릿     2  160
16  부산  태블릿     1   70
17  대전  태블릿     3  135
18  서울  노트북     2  120
19  부산  태블릿     2  140

In [439]:
# 지역별 판매 기록의 개수
sales_df['지역'].value_counts()

지역
서울    7
부산    7
대전    6
Name: count, dtype: int64

In [440]:
# 상품별 판매 기록의 개수와 비율
sales_df['상품'].value_counts(normalize=True)

상품
노트북    0.5
태블릿    0.5
Name: proportion, dtype: float64

In [441]:
# 지역과 상품의 조합별 판매 기록 개수
sales_df.value_counts(['지역', '상품'])

지역  상품
서울  노트북    4
부산  태블릿    4
서울  태블릿    3
부산  노트북    3
대전  노트북    3
    태블릿    3
Name: count, dtype: int64

In [442]:
sample_df = pd.read_csv('data/sample_data.csv')
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [443]:
sample_df['City'].value_counts(dropna=False, ascending=True)

City
Los Angeles    1
NaN            1
Chicago        1
New York       2
Houston        2
Name: count, dtype: int64

In [444]:
# 지역별 총매출
sales_df.groupby(by = '지역')['매출'].sum()

지역
대전    585
부산    850
서울    850
Name: 매출, dtype: int64

In [445]:
# 상품별 평균 매출 -> 상품을 기준으로 매출의 평균
sales_df.groupby(by = '상품')['매출'].mean()

상품
노트북    112.5
태블릿    116.0
Name: 매출, dtype: float64

In [446]:
# 지역별 판매수량의 합계와 매출의 합계 -> 지역을 기준으로 판매수량과 각각의 매출의 합계
sales_df.groupby(by = '지역', as_index=False)[['판매수량', '매출']].sum()

   지역  판매수량   매출
0  대전    11  585
1  부산    13  850
2  서울    13  850

In [447]:
# 지역과 상품별 평균 매출 -> 지역과 상품을 기준으로 매출의 평균
sales_df.groupby(by = ['지역', '상품'], as_index=False)['매출'].mean()

   지역   상품          매출
0  대전  노트북  105.000000
1  대전  태블릿   90.000000
2  부산  노트북  120.000000
3  부산  태블릿  122.500000
4  서울  노트북  112.500000
5  서울  태블릿  133.333333

In [448]:
sales_df.pivot_table(
    values='매출',
    aggfunc='mean',
    index='지역',
    columns='상품'
)

상품    노트북         태블릿
지역
대전  105.0   90.000000
부산  120.0  122.500000
서울  112.5  133.333333

In [449]:

# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시
sales_df.pivot_table(
    index='지역',
    columns='상품',
    values='매출',
    aggfunc='sum', 
    margins=True
)

상품    노트북   태블릿   All
지역
대전    315   270   585
부산    360   490   850
서울    450   400   850
All  1125  1160  2285

In [450]:
# 지역별 매출 : 건수, 합계, 평균, 최대값
sales_df.groupby(by='지역')['매출'].agg(['count', 'sum', 'mean', 'max'])

    count  sum        mean  max
지역
대전      6  585   97.500000  135
부산      7  850  121.428571  210
서울      7  850  121.428571  160

## 5-1.결측치 처리

In [451]:
import pandas as pd
sample_df = pd.read_csv('data/sample_data.csv')
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [452]:
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     5 non-null      float64
 2   Gender  7 non-null      str
 3   City    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 356.0 bytes

In [453]:
# isna
sample_df.isna()

    Name    Age  Gender   City
0  False  False   False  False
1  False   True   False  False
2  False  False   False   True
3  False  False   False  False
4  False   True   False  False
5  False  False   False  False
6  False  False   False  False

In [454]:
sample_df['Age'].isna()

0    False
1     True
2    False
3    False
4     True
5    False
6    False
Name: Age, dtype: bool

In [455]:
sample_df.isna().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [456]:
# isnull() : 결측치 여부 확인
sample_df.isnull()

    Name    Age  Gender   City
0  False  False   False  False
1  False   True   False  False
2  False  False   False   True
3  False  False   False  False
4  False   True   False  False
5  False  False   False  False
6  False  False   False  False

In [457]:
sample_df.isna().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [458]:
# 결측치가 있는 데이터 확인
# Age 컬럼에 결측치가 있는지와 결측치 데이터 확인
print(sample_df['Age'].isna().sum())
sample_df[sample_df['Age'].isna()]

2

     Name  Age Gender         City
1     Bob  NaN      M  Los Angeles
4  Edward  NaN      M      Houston

In [459]:
# 어떤 컬럼에든 결측치가 있는 데이터의 갯수, 데이터 확인
na_df = sample_df[sample_df.isna().any(axis=1)]
print(len(na_df))
na_df

3

      Name   Age Gender         City
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
4   Edward   NaN      M      Houston

In [460]:
# 결측치가 있는 데이터 삭제 : dropna

#결측치가 있는 값은 모두 지운다
sample_df.dropna()

    Name   Age Gender      City
0  Alice  24.0      F  New York
3  David  29.0      M   Chicago
5  Alice  24.0      F  New York
6  Susan  32.0      F   Houston

In [461]:
# City 컬럼에 결측치가 있는 값만 지운다
sample_df.dropna(subset=['City'])

     Name   Age Gender         City
0   Alice  24.0      F     New York
1     Bob   NaN      M  Los Angeles
3   David  29.0      M      Chicago
4  Edward   NaN      M      Houston
5   Alice  24.0      F     New York
6   Susan  32.0      F      Houston

In [462]:
# Age와 City 컬럼에 결측치가 있는 값만 지운다
sample_df.dropna(subset=['Age', 'City'])

    Name   Age Gender      City
0  Alice  24.0      F  New York
3  David  29.0      M   Chicago
5  Alice  24.0      F  New York
6  Susan  32.0      F   Houston

In [463]:
# Age 걸측치는 Age의 평균값으로 채우기
age_avg = sample_df['Age'].mean()
sample_df['Age'] = sample_df['Age'].fillna(sample_df['Age'].mean())
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob  26.2      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward  26.2      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

## 5-2. 중복치 처리

In [464]:
# 중복값 확인
sample_df.duplicated().sum()

np.int64(1)

In [465]:
sample_df.duplicated().sum()

np.int64(1)

In [466]:
# 중복값이 데이터 확인
sample_df[sample_df.duplicated()]

    Name   Age Gender      City
5  Alice  24.0      F  New York

In [467]:
# 중복값 삭제
sample_df.drop_duplicates()
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob  26.2      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward  26.2      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston