## 결측치 처리

In [183]:
import pandas as pd

url = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df = pd.read_csv(url, sep='\t')
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [184]:
new_columns=['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked']
titanic_df.columns=new_columns
titanic_df.columns

Index(['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [185]:
titanic_df['age'][titanic_df['age'].isna()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [186]:
titanic_df['age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154     True
155    False
Name: age, Length: 156, dtype: bool

In [187]:
titanic_df['age'][titanic_df['age'].isnull()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [188]:
titanic_df['age'][titanic_df['age'].isnull()].isnull().sum()

np.int64(30)

In [189]:
titanic_df['age'].notnull()

0       True
1       True
2       True
3       True
4       True
       ...
151     True
152     True
153     True
154    False
155     True
Name: age, Length: 156, dtype: bool

In [190]:
titanic_df['age'][titanic_df['age'].notnull()]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
150    51.0
151    22.0
152    55.5
153    40.5
155    51.0
Name: age, Length: 126, dtype: float64

In [191]:
titanic_df.loc[titanic_df['age'].notnull(), ['age', 'name']]

      age                                               name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
150  51.0                         Bateman, Rev. Robert James
151  22.0                  Pears, Mrs. Thomas (Edith Wearne)
152  55.5                                   Meo, Mr. Alfonzo
153  40.5                    van Billiard, Mr. Austin Blyler
155  51.0                        Williams, Mr. Charles Duane

[126 rows x 2 columns]

In [192]:
titanic_df.loc[titanic_df['age'].isnull(), ['age', 'name']]

     age                                            name
5    NaN                                Moran, Mr. James
17   NaN                    Williams, Mr. Charles Eugene
19   NaN                         Masselmani, Mrs. Fatima
26   NaN                         Emir, Mr. Farred Chehab
28   NaN                   O'Dwyer, Miss. Ellen "Nellie"
29   NaN                             Todoroff, Mr. Lalio
31   NaN  Spencer, Mrs. William Augustus (Marie Eugenie)
32   NaN                        Glynn, Miss. Mary Agatha
36   NaN                                Mamee, Mr. Hanna
42   NaN                             Kraeff, Mr. Theodor
45   NaN                        Rogers, Mr. William John
46   NaN                               Lennon, Mr. Denis
47   NaN                       O'Driscoll, Miss. Bridget
48   NaN                             Samaan, Mr. Youssef
55   NaN                               Woolner, Mr. Hugh
64   NaN                           Stewart, Mr. Albert A
65   NaN                        Moubarek, Master. Gerios
76   NaN                               Staneff, Mr. Ivan
77   NaN                        Moutal, Mr. Rahamin Haim
82   NaN                  McDermott, Miss. Brigdet Delia
87   NaN                   Slocovski, Mr. Selman Francis
95   NaN                     Shorney, Mr. Charles Joseph
101  NaN                Petroff, Mr. Pastcho ("Pentcho")
107  NaN                          Moss, Mr. Albert Johan
109  NaN                             Moran, Miss. Bertha
121  NaN                      Moore, Mr. Leonard Charles
126  NaN                             McMahon, Mr. Martin
128  NaN                               Peter, Miss. Anna
140  NaN                   Boulos, Mrs. Joseph (Sultana)
154  NaN                           Olsen, Mr. Ole Martin

In [193]:
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [194]:
titanic_df['cabin']=titanic_df['cabin'].fillna('N')
titanic_df['cabin']

0         N
1       C85
2         N
3      C123
4         N
       ...
151      C2
152       N
153       N
154       N
155       N
Name: cabin, Length: 156, dtype: str

In [195]:
titanic_df['cabin'].value_counts()

cabin
N              125
C123             2
C23 C25 C27      2
D26              2
C85              1
E46              1
G6               1
C103             1
D56              1
A6               1
B78              1
D33              1
B30              1
C52              1
B28              1
C83              1
F33              1
F G73            1
E31              1
A5               1
D10 D12          1
C110             1
B58 B60          1
E101             1
F E69            1
D47              1
B86              1
F2               1
C2               1
Name: count, dtype: int64

In [196]:
titanic_df['cabin'][0]

'N'

In [197]:
titanic_df['cabin']=titanic_df['cabin'].apply(lambda x : x[0])
titanic_df['cabin']

0      N
1      C
2      N
3      C
4      N
      ..
151    C
152    N
153    N
154    N
155    N
Name: cabin, Length: 156, dtype: str

In [198]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerId  156 non-null    int64
 1   survived     156 non-null    int64
 2   pclass       156 non-null    int64
 3   name         156 non-null    str
 4   sex          156 non-null    str
 5   age          126 non-null    float64
 6   sibsp        156 non-null    int64
 7   parch        156 non-null    int64
 8   ticket       156 non-null    str
 9   fare         156 non-null    float64
 10  cabin        156 non-null    str
 11  embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [199]:
titanic_df_copy=titanic_df.copy()
titanic_df_copy

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [200]:
copy_titanic_df=titanic_df.copy()
copy_titanic_df

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [201]:
titanic_df_copy['age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154     True
155    False
Name: age, Length: 156, dtype: bool

In [202]:
titanic_df_copy['age']=titanic_df_copy['age'].fillna(titanic_df_copy['age'].mean())
titanic_df_copy['age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
151    22.000000
152    55.500000
153    40.500000
154    28.141508
155    51.000000
Name: age, Length: 156, dtype: float64

In [203]:
hex(id(titanic_df))

'0x298cdeb1e80'

In [204]:
hex(id(copy_titanic_df))

'0x298cdeb3a80'

In [205]:
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [206]:
copy_titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [207]:
copy_titanic_df['age']=0
copy_titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,0,373450,8.0500,N,S

In [208]:
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [209]:
titanic_df1=titanic_df[['survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'fare']]
titanic_df2=titanic_df1.apply(pd.to_numeric, errors='coerce')
titanic_df2

     survived  pclass  name  sex   age  sibsp  parch     fare
0           0       3   NaN  NaN  22.0      1      0   7.2500
1           1       1   NaN  NaN  38.0      1      0  71.2833
2           1       3   NaN  NaN  26.0      0      0   7.9250
3           1       1   NaN  NaN  35.0      1      0  53.1000
4           0       3   NaN  NaN  35.0      0      0   8.0500
..        ...     ...   ...  ...   ...    ...    ...      ...
151         1       1   NaN  NaN  22.0      1      0  66.6000
152         0       3   NaN  NaN  55.5      0      0   8.0500
153         0       3   NaN  NaN  40.5      0      2  14.5000
154         0       3   NaN  NaN   NaN      0      0   7.3125
155         0       1   NaN  NaN  51.0      0      1  61.3792

[156 rows x 8 columns]

In [210]:
titanic_df2.dtypes

survived      int64
pclass        int64
name        float64
sex         float64
age         float64
sibsp         int64
parch         int64
fare        float64
dtype: object

In [211]:
titanic_df2['survived']=titanic_df2['survived'].astype('float')
titanic_df2['pclass']=titanic_df2['pclass'].astype('float')
titanic_df2['age']=titanic_df2['age'].astype('float')
titanic_df2['sibsp']=titanic_df2['sibsp'].astype('float')
titanic_df2['parch']=titanic_df2['parch'].astype('float')
titanic_df2['fare']=titanic_df2['fare'].astype('float')
titanic_df2.dtypes

survived    float64
pclass      float64
name        float64
sex         float64
age         float64
sibsp       float64
parch       float64
fare        float64
dtype: object

In [212]:
titanic_df1=titanic_df[['survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'fare']]

tmp=[]
for each in titanic_df1['sex']:
    if each=='female':
        tmp.append(0)
    else:
        tmp.append(1)

titanic_df1['gender']=tmp
titanic_df1

,survived,pclass,name,sex,age,sibsp,parch,fare,gender
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,1
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,0
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,0
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,1
...,...,...,...,...,...,...,...,...,...
151,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,66.6000,0
152,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,8.0500,1
153,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,14.5000,1
154,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,7.3125,1
155,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,61.3792,1

## 판다스의 통계 함수

In [213]:
titanic_df.sum()

passengerId                                                12246
survived                                                      54
pclass                                                       378
name           Braund, Mr. Owen HarrisCumings, Mrs. John Brad...
sex            malefemalefemalefemalemalemalemalemalefemalefe...
age                                                      3545.83
sibsp                                                         96
parch                                                         62
ticket         A/5 21171PC 17599STON/O2. 31012821138033734503...
fare                                                   4385.0956
cabin          NCNCNNENNNGCNNNNNNNNNDNANNNCNNNBNNNNNNNNNNNNNN...
embarked       SCSSSQSSSCSSSSSSQSSCSSQSSSCSQSCCQSCSCSSCSSCCQS...
dtype: object

In [214]:
titanic_df.count()

passengerId    156
survived       156
pclass         156
name           156
sex            156
age            126
sibsp          156
parch          156
ticket         156
fare           156
cabin          156
embarked       155
dtype: int64

In [215]:
titanic_df.max()

passengerId                                156
survived                                     1
pclass                                       3
name           van Billiard, Mr. Austin Blyler
sex                                       male
age                                       71.0
sibsp                                        5
parch                                        5
ticket                             W.E.P. 5734
fare                                     263.0
cabin                                        N
embarked                                     S
dtype: object

In [216]:
titanic_df.min()

passengerId                                                 1
survived                                                    0
pclass                                                      1
name           Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
sex                                                    female
age                                                      0.83
sibsp                                                       0
parch                                                       0
ticket                                                 110465
fare                                                     6.75
cabin                                                       A
embarked                                                    C
dtype: object

In [217]:
titanic_df.mean(numeric_only=True)

passengerId    78.500000
survived        0.346154
pclass          2.423077
age            28.141508
sibsp           0.615385
parch           0.397436
fare           28.109587
dtype: float64

In [218]:
titanic_df.median(numeric_only=True)

passengerId    78.5000
survived        0.0000
pclass          3.0000
age            26.0000
sibsp           0.0000
parch           0.0000
fare           14.4542
dtype: float64

In [219]:
titanic_df.mode(numeric_only=True)

     passengerId  survived  pclass   age  sibsp  parch  fare
0              1       0.0     3.0  21.0    0.0    0.0  8.05
1              2       NaN     NaN   NaN    NaN    NaN   NaN
2              3       NaN     NaN   NaN    NaN    NaN   NaN
3              4       NaN     NaN   NaN    NaN    NaN   NaN
4              5       NaN     NaN   NaN    NaN    NaN   NaN
..           ...       ...     ...   ...    ...    ...   ...
151          152       NaN     NaN   NaN    NaN    NaN   NaN
152          153       NaN     NaN   NaN    NaN    NaN   NaN
153          154       NaN     NaN   NaN    NaN    NaN   NaN
154          155       NaN     NaN   NaN    NaN    NaN   NaN
155          156       NaN     NaN   NaN    NaN    NaN   NaN

[156 rows x 7 columns]

In [221]:
titanic_df.var(numeric_only=True)

passengerId    2041.000000
survived          0.227792
pclass            0.632754
age             213.565487
sibsp             1.115633
parch             0.757155
fare           1552.442481
dtype: float64

In [222]:
titanic_df.std(numeric_only=True)

passengerId    45.177428
survived        0.477275
pclass          0.795459
age            14.613880
sibsp           1.056235
parch           0.870146
fare           39.401047
dtype: float64

In [223]:
titanic_df.skew(numeric_only=True)

passengerId    0.000000
survived       0.653058
pclass        -0.912744
age            0.700367
sibsp          2.220685
parch          2.760421
fare           4.176408
dtype: float64

In [224]:
titanic_df.kurt(numeric_only=True)

passengerId    -1.200000
survived       -1.594120
pclass         -0.803872
age             0.613747
sibsp           4.996881
parch           9.346662
fare           21.109985
dtype: float64