In [5]:
import pandas as pd
pd.__version__

'3.0.5'

In [9]:
score = [['홍길동', 100, 90, 80]]
score_df = pd.DataFrame(score, columns=['이름', '국어', '영어', '수학'])
score_df

    이름   국어  영어  수학
0  홍길동  100  90  80

In [11]:
score_df.reset_index(drop=True)

    이름   국어  영어  수학
0  홍길동  100  90  80